const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });
const { Client } = require('pg');

const runMigration = async () => {
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false }
  });

  try {
    await client.connect();
    console.log('Connected to Supabase PostgreSQL!');

    const sql = `
      CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL CHECK(role IN ('Admin', 'Manager', 'Cashier')),
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS products (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
        price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
        cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
        stock_quantity INTEGER NOT NULL DEFAULT 0,
        min_stock_level INTEGER NOT NULL DEFAULT 5,
        size TEXT, 
        color TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id),
        customer_name TEXT, 
        total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
        status TEXT DEFAULT 'Closed' CHECK(status IN ('Open', 'Closed')),
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS order_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
        product_id BIGINT REFERENCES products(id),
        quantity INTEGER NOT NULL DEFAULT 1,
        unit_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
        unit_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
        subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00
      );

      CREATE TABLE IF NOT EXISTS payments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
        amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
        method TEXT NOT NULL CHECK(method IN ('Cash', 'Card', 'Mobile')),
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS audit_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        action TEXT NOT NULL,
        details TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      -- Seed Initial Data
      INSERT INTO users (id, username, password_hash, role) VALUES 
      (1, 'admin', 'password', 'Admin'),
      (2, 'manager', 'password', 'Manager'),
      (3, 'cashier', 'password', 'Cashier')
      ON CONFLICT (id) DO NOTHING;

      INSERT INTO categories (id, name) VALUES 
      (1, 'Sweaters'), 
      (2, 'Hoodies'), 
      (3, 'Shirts'), 
      (4, 'Shoes'),
      (5, 'Accessories')
      ON CONFLICT (id) DO NOTHING;

      INSERT INTO products (id, name, category_id, price, stock_quantity, size, color) VALUES 
      (1, 'Classic Knit Sweater', 1, 45.00, 20, 'M', 'Navy'),
      (2, 'Classic Knit Sweater', 1, 45.00, 15, 'L', 'Navy'),
      (3, 'Heavyweight Zip Hoodie', 2, 55.00, 30, 'L', 'Black'),
      (4, 'Basic Cotton T-Shirt', 3, 15.00, 100, 'M', 'White'),
      (5, 'Running Sneakers', 4, 85.00, 10, '10', 'Grey'),
      (6, 'Canvas High Tops', 4, 60.00, 25, '9', 'White')
      ON CONFLICT (id) DO NOTHING;
    `;

    console.log('Running migrations...');
    await client.query(sql);
    console.log('Migrations completed successfully!');
  } catch (err) {
    console.error('Migration failed:', err);
  } finally {
    await client.end();
  }
};

runMigration();
