const { makeReceiptCode } = require('./utils/receiptCode');

const sqliteExec = (db, sql) => new Promise((resolve, reject) => {
  db.run(sql, (err) => (err ? reject(err) : resolve()));
});

const sqliteTry = (db, sql) => new Promise((resolve) => {
  db.run(sql, () => resolve());
});

const warnUnlessExists = (label, error) => {
  if (!/already exists|duplicate/i.test(error.message || '')) {
    console.warn(`${label}:`, error.message);
  }
};

const engine = () => require('./db').getEngine();
const queries = () => {
  const db = require('./db');
  return { runQuery: db.runQuery, allQuery: db.allQuery };
};

// Core tables for Postgres. SQLite gets these from schema.sql; Postgres previously relied on a
// manual run of migrate_supabase.js, so an empty Supabase DB had no tables at all.
const POSTGRES_BASE_SQL = `
  CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Admin', 'Manager', 'Cashier')),
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    price NUMERIC(10,2) NOT NULL DEFAULT 0,
    cost NUMERIC(10,2) NOT NULL DEFAULT 0,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    min_stock_level INTEGER NOT NULL DEFAULT 5,
    size TEXT,
    color TEXT,
    barcode TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    customer_name TEXT,
    customer_phone TEXT,
    total_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    status TEXT DEFAULT 'Closed' CHECK (status IN ('Open', 'Closed')),
    receipt_code TEXT,
    close_id INTEGER,
    voided INTEGER DEFAULT 0,
    vat_rate NUMERIC(5,2) DEFAULT 16,
    vat_amount NUMERIC(10,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(10,2) NOT NULL DEFAULT 0,
    unit_cost NUMERIC(10,2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(10,2) NOT NULL DEFAULT 0
  );
  CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    method TEXT NOT NULL CHECK (method IN ('Cash', 'Card', 'Mobile')),
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
  CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );
`;

const ID_TABLES = [
  'users', 'categories', 'products', 'orders', 'order_items', 'payments', 'audit_logs',
  'day_closes', 'customers', 'sms_campaigns', 'sms_messages', 'returns', 'return_items',
  'voids', 'stock_intakes'
];

const ensurePostgresBase = async () => {
  const { databaseType, pool } = engine();
  if (databaseType !== 'postgres' || !pool) return;

  // Errors here are fatal: without the core tables the API cannot work.
  await pool.query(POSTGRES_BASE_SQL);

  const isEmpty = async (table) => {
    const { rows } = await pool.query(`SELECT COUNT(*)::int AS c FROM ${table}`);
    return rows[0].c === 0;
  };

  if (await isEmpty('users')) {
    console.log('Seeding default users (admin / manager / cashier).');
    await pool.query(`
      INSERT INTO users (username, password_hash, role) VALUES
      ('admin', 'password', 'Admin'),
      ('manager', 'password', 'Manager'),
      ('cashier', 'password', 'Cashier')
      ON CONFLICT (username) DO NOTHING
    `);
  }
  if (await isEmpty('categories')) {
    await pool.query(`
      INSERT INTO categories (name) VALUES
      ('Sweaters'), ('Hoodies'), ('Shirts'), ('Shoes'), ('Accessories')
      ON CONFLICT (name) DO NOTHING
    `);
  }
  if (await isEmpty('products')) {
    await pool.query(`
      INSERT INTO products (name, category_id, price, stock_quantity, size, color)
      SELECT v.name, c.id, v.price, v.stock, v.size, v.color
      FROM (VALUES
        ('Classic Knit Sweater', 'Sweaters', 45.00, 20, 'M', 'Navy'),
        ('Classic Knit Sweater', 'Sweaters', 45.00, 15, 'L', 'Navy'),
        ('Heavyweight Zip Hoodie', 'Hoodies', 55.00, 30, 'L', 'Black'),
        ('Basic Cotton T-Shirt', 'Shirts', 15.00, 100, 'M', 'White'),
        ('Running Sneakers', 'Shoes', 85.00, 10, '10', 'Grey'),
        ('Canvas High Tops', 'Shoes', 60.00, 25, '9', 'White')
      ) AS v(name, category, price, stock, size, color)
      LEFT JOIN categories c ON c.name = v.category
    `);
  }
};

// Rows inserted with explicit ids (e.g. by migrate_supabase.js) don't advance the id counter,
// which makes the next INSERT fail with "duplicate key". Move every counter past MAX(id).
const resyncPostgresSequences = async () => {
  const { databaseType, pool } = engine();
  if (databaseType !== 'postgres' || !pool) return;
  for (const table of ID_TABLES) {
    try {
      await pool.query(`
        SELECT setval(seq::regclass, COALESCE((SELECT MAX(id) FROM ${table}), 0) + 1, false)
        FROM pg_get_serial_sequence('${table}', 'id') AS seq
        WHERE seq IS NOT NULL
      `);
    } catch (error) {
      console.warn(`sequence resync (${table}):`, error.message);
    }
  }
};

const ensureReceiptCodes = async () => {
  const { databaseType, pool, db } = engine();
  const { runQuery, allQuery } = queries();

  try {
    if (databaseType === 'postgres' && pool) {
      await pool.query('ALTER TABLE orders ADD COLUMN IF NOT EXISTS receipt_code TEXT');
      await pool.query('CREATE UNIQUE INDEX IF NOT EXISTS orders_receipt_code_uidx ON orders (receipt_code)');
    } else if (db) {
      await sqliteTry(db, 'ALTER TABLE orders ADD COLUMN receipt_code TEXT');
    }
  } catch (error) {
    warnUnlessExists('receipt_code column', error);
  }

  try {
    const rows = await allQuery(`SELECT id FROM orders WHERE receipt_code IS NULL OR receipt_code = ''`);
    for (const row of rows) {
      await runQuery(`UPDATE orders SET receipt_code = ? WHERE id = ?`, [makeReceiptCode(row.id), row.id]);
    }
  } catch (error) {
    console.warn('receipt_code backfill:', error.message);
  }
};

const ensureDayCloses = async () => {
  const { databaseType, pool, db } = engine();

  try {
    if (databaseType === 'postgres' && pool) {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS day_closes (
          id SERIAL PRIMARY KEY,
          user_id INTEGER,
          business_date DATE NOT NULL,
          closed_at TIMESTAMPTZ DEFAULT NOW(),
          sales_count INTEGER NOT NULL DEFAULT 0,
          sales_total NUMERIC(10,2) NOT NULL DEFAULT 0,
          items_sold INTEGER NOT NULL DEFAULT 0
        )
      `);
      await pool.query('ALTER TABLE orders ADD COLUMN IF NOT EXISTS close_id INTEGER');
      await pool.query('ALTER TABLE day_closes ADD COLUMN IF NOT EXISTS opening_float NUMERIC(10,2) DEFAULT 0');
      await pool.query('ALTER TABLE day_closes ADD COLUMN IF NOT EXISTS cash_sales NUMERIC(10,2) DEFAULT 0');
      await pool.query('ALTER TABLE day_closes ADD COLUMN IF NOT EXISTS cash_refunds NUMERIC(10,2) DEFAULT 0');
      await pool.query('ALTER TABLE day_closes ADD COLUMN IF NOT EXISTS cash_extras NUMERIC(10,2) DEFAULT 0');
      await pool.query('ALTER TABLE day_closes ADD COLUMN IF NOT EXISTS expected_cash NUMERIC(10,2) DEFAULT 0');
      await pool.query('ALTER TABLE day_closes ADD COLUMN IF NOT EXISTS counted_cash NUMERIC(10,2)');
      await pool.query('ALTER TABLE day_closes ADD COLUMN IF NOT EXISTS variance NUMERIC(10,2) DEFAULT 0');
    } else if (db) {
      await sqliteExec(db, `
        CREATE TABLE IF NOT EXISTS day_closes (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          user_id INTEGER REFERENCES users(id),
          business_date DATE NOT NULL,
          closed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
          sales_count INTEGER NOT NULL DEFAULT 0,
          sales_total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
          items_sold INTEGER NOT NULL DEFAULT 0
        )
      `);
      await sqliteTry(db, 'ALTER TABLE orders ADD COLUMN close_id INTEGER');
      await sqliteTry(db, 'ALTER TABLE day_closes ADD COLUMN opening_float DECIMAL(10,2) DEFAULT 0');
      await sqliteTry(db, 'ALTER TABLE day_closes ADD COLUMN cash_sales DECIMAL(10,2) DEFAULT 0');
      await sqliteTry(db, 'ALTER TABLE day_closes ADD COLUMN cash_refunds DECIMAL(10,2) DEFAULT 0');
      await sqliteTry(db, 'ALTER TABLE day_closes ADD COLUMN cash_extras DECIMAL(10,2) DEFAULT 0');
      await sqliteTry(db, 'ALTER TABLE day_closes ADD COLUMN expected_cash DECIMAL(10,2) DEFAULT 0');
      await sqliteTry(db, 'ALTER TABLE day_closes ADD COLUMN counted_cash DECIMAL(10,2)');
      await sqliteTry(db, 'ALTER TABLE day_closes ADD COLUMN variance DECIMAL(10,2) DEFAULT 0');
    }
  } catch (error) {
    warnUnlessExists('day_closes setup', error);
  }
};

const ensureCustomersAndSms = async () => {
  const { databaseType, pool, db } = engine();

  try {
    if (databaseType === 'postgres' && pool) {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS customers (
          id SERIAL PRIMARY KEY,
          name TEXT,
          phone TEXT NOT NULL UNIQUE,
          created_at TIMESTAMPTZ DEFAULT NOW()
        )
      `);
      await pool.query(`
        CREATE TABLE IF NOT EXISTS sms_campaigns (
          id SERIAL PRIMARY KEY,
          user_id INTEGER,
          title TEXT,
          message TEXT NOT NULL,
          recipient_count INTEGER NOT NULL DEFAULT 0,
          sent_count INTEGER NOT NULL DEFAULT 0,
          failed_count INTEGER NOT NULL DEFAULT 0,
          status TEXT,
          created_at TIMESTAMPTZ DEFAULT NOW()
        )
      `);
      await pool.query(`
        CREATE TABLE IF NOT EXISTS sms_messages (
          id SERIAL PRIMARY KEY,
          campaign_id INTEGER,
          customer_id INTEGER,
          phone TEXT NOT NULL,
          status TEXT,
          provider_ref TEXT,
          error TEXT,
          created_at TIMESTAMPTZ DEFAULT NOW()
        )
      `);
      await pool.query('ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_phone TEXT');
    } else if (db) {
      await sqliteExec(db, `
        CREATE TABLE IF NOT EXISTS customers (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT,
          phone TEXT NOT NULL UNIQUE,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
      `);
      await sqliteExec(db, `
        CREATE TABLE IF NOT EXISTS sms_campaigns (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          user_id INTEGER,
          title TEXT,
          message TEXT NOT NULL,
          recipient_count INTEGER NOT NULL DEFAULT 0,
          sent_count INTEGER NOT NULL DEFAULT 0,
          failed_count INTEGER NOT NULL DEFAULT 0,
          status TEXT,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
      `);
      await sqliteExec(db, `
        CREATE TABLE IF NOT EXISTS sms_messages (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          campaign_id INTEGER,
          customer_id INTEGER,
          phone TEXT NOT NULL,
          status TEXT,
          provider_ref TEXT,
          error TEXT,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
      `);
      await sqliteTry(db, 'ALTER TABLE orders ADD COLUMN customer_phone TEXT');
    }
  } catch (error) {
    warnUnlessExists('customers/sms setup', error);
  }
};

const ensureReturns = async () => {
  const { databaseType, pool, db } = engine();

  try {
    if (databaseType === 'postgres' && pool) {
      await pool.query(`
        CREATE TABLE IF NOT EXISTS returns (
          id SERIAL PRIMARY KEY,
          order_id INTEGER,
          user_id INTEGER,
          return_code TEXT UNIQUE,
          type TEXT NOT NULL,
          refund_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
          extra_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
          method TEXT,
          reason TEXT,
          restock INTEGER NOT NULL DEFAULT 1,
          created_at TIMESTAMPTZ DEFAULT NOW()
        )
      `);
      await pool.query(`
        CREATE TABLE IF NOT EXISTS return_items (
          id SERIAL PRIMARY KEY,
          return_id INTEGER,
          order_item_id INTEGER,
          product_id INTEGER,
          quantity INTEGER NOT NULL DEFAULT 1,
          unit_price NUMERIC(10,2) NOT NULL DEFAULT 0,
          unit_cost NUMERIC(10,2) NOT NULL DEFAULT 0,
          kind TEXT NOT NULL
        )
      `);
    } else if (db) {
      await sqliteExec(db, `
        CREATE TABLE IF NOT EXISTS returns (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          order_id INTEGER REFERENCES orders(id),
          user_id INTEGER REFERENCES users(id),
          return_code TEXT UNIQUE,
          type TEXT NOT NULL CHECK(type IN ('return', 'exchange')),
          refund_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
          extra_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
          method TEXT CHECK(method IN ('Cash', 'Card', 'Mobile')),
          reason TEXT,
          restock INTEGER NOT NULL DEFAULT 1,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
      `);
      await sqliteExec(db, `
        CREATE TABLE IF NOT EXISTS return_items (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          return_id INTEGER REFERENCES returns(id) ON DELETE CASCADE,
          order_item_id INTEGER REFERENCES order_items(id),
          product_id INTEGER REFERENCES products(id),
          quantity INTEGER NOT NULL DEFAULT 1,
          unit_price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
          unit_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
          kind TEXT NOT NULL CHECK(kind IN ('returned', 'taken'))
        )
      `);
    }
  } catch (error) {
    warnUnlessExists('returns setup', error);
  }
};

const ensureProductBarcodes = async () => {
  const { databaseType, pool, db } = engine();
  try {
    if (databaseType === 'postgres' && pool) {
      await pool.query('ALTER TABLE products ADD COLUMN IF NOT EXISTS barcode TEXT');
      await pool.query(`CREATE UNIQUE INDEX IF NOT EXISTS products_barcode_uidx ON products (barcode) WHERE barcode IS NOT NULL AND barcode <> ''`);
    } else if (db) {
      await sqliteTry(db, 'ALTER TABLE products ADD COLUMN barcode TEXT');
      await sqliteTry(db, `CREATE UNIQUE INDEX IF NOT EXISTS products_barcode_uidx ON products (barcode) WHERE barcode IS NOT NULL AND barcode <> ''`);
    }
  } catch (error) {
    warnUnlessExists('product barcode', error);
  }
};

const ensureVoidsVatAndStock = async () => {
  const { databaseType, pool, db } = engine();
  try {
    if (databaseType === 'postgres' && pool) {
      await pool.query('ALTER TABLE orders ADD COLUMN IF NOT EXISTS voided INTEGER DEFAULT 0');
      await pool.query('ALTER TABLE orders ADD COLUMN IF NOT EXISTS vat_rate NUMERIC(5,2) DEFAULT 16');
      await pool.query('ALTER TABLE orders ADD COLUMN IF NOT EXISTS vat_amount NUMERIC(10,2) DEFAULT 0');
      await pool.query(`
        CREATE TABLE IF NOT EXISTS voids (
          id SERIAL PRIMARY KEY,
          order_id INTEGER,
          user_id INTEGER,
          reason TEXT,
          restock INTEGER NOT NULL DEFAULT 1,
          created_at TIMESTAMPTZ DEFAULT NOW()
        )
      `);
      await pool.query(`
        CREATE TABLE IF NOT EXISTS stock_intakes (
          id SERIAL PRIMARY KEY,
          product_id INTEGER,
          user_id INTEGER,
          quantity INTEGER NOT NULL,
          unit_cost NUMERIC(10,2) NOT NULL DEFAULT 0,
          note TEXT,
          created_at TIMESTAMPTZ DEFAULT NOW()
        )
      `);
    } else if (db) {
      await sqliteTry(db, 'ALTER TABLE orders ADD COLUMN voided INTEGER DEFAULT 0');
      await sqliteTry(db, 'ALTER TABLE orders ADD COLUMN vat_rate DECIMAL(5,2) DEFAULT 16');
      await sqliteTry(db, 'ALTER TABLE orders ADD COLUMN vat_amount DECIMAL(10,2) DEFAULT 0');
      await sqliteExec(db, `
        CREATE TABLE IF NOT EXISTS voids (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          order_id INTEGER REFERENCES orders(id),
          user_id INTEGER REFERENCES users(id),
          reason TEXT,
          restock INTEGER NOT NULL DEFAULT 1,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
      `);
      await sqliteExec(db, `
        CREATE TABLE IF NOT EXISTS stock_intakes (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          product_id INTEGER REFERENCES products(id),
          user_id INTEGER REFERENCES users(id),
          quantity INTEGER NOT NULL,
          unit_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
          note TEXT,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
      `);
    }
  } catch (error) {
    warnUnlessExists('voids/vat/stock setup', error);
  }
};

const hashExistingPasswords = async () => {
  const { isHashed, hashPassword } = require('./utils/password');
  const { allQuery, runQuery } = queries();
  try {
    const rows = await allQuery(`SELECT id, password_hash FROM users`);
    for (const row of rows) {
      if (isHashed(row.password_hash)) continue;
      await runQuery(`UPDATE users SET password_hash = ? WHERE id = ?`, [await hashPassword(row.password_hash), row.id]);
    }
  } catch (error) {
    console.warn('password hash migrate:', error.message);
  }
};

const ensureSchema = async () => {
  await ensurePostgresBase();
  await ensureReceiptCodes();
  await ensureDayCloses();
  await ensureCustomersAndSms();
  await ensureReturns();
  await ensureProductBarcodes();
  await ensureVoidsVatAndStock();
  await hashExistingPasswords();
  await resyncPostgresSequences();
};

module.exports = { ensureSchema };
